# Problem 1

## Introduction

Say "Hello, World!" With Python

In [1]:
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


Python If-Else

In [2]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
    
    if n % 2 == 1:
        print("Weird")
    elif n < 5:
        print("Not Weird")
    elif n <= 20:
        print("Weird")
    else:
        print("Not Weird")

3
Weird


Arithmetic Operators

In [3]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    
    print(f"{a+b}\n{a-b}\n{a*b}")

8
-2
6
10
-16


Python: Division

In [4]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    
    print(f"{a//b}\n{a/b}")

3
5
0
0.6


Loops

In [5]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i**2)

3
0
1
4


Write a function

In [6]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    if year % 400 == 0 or (year % 4 == 0 and year % 100 != 0):
        leap = True
    
    return leap

year = int(input())
print(is_leap(year))

1990
False


Print Function

In [7]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n):
        print(i + 1, end="")

3
123

## Data types

List Comprehensions

In [8]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
    
    print([[i, j, k] for i in range(x + 1) \
                     for j in range(y + 1) \
                     for k in range(z + 1) \
                     if i + j + k != n])

1
1
2
3
[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 2]]


Find the Runner-Up Score!

In [10]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    
    arr_set = set(arr)
    arr_set.remove(max(arr_set))
    print(max(arr_set))

5
2 3 6 6 5
5


Nested Lists

In [11]:
if __name__ == '__main__':
    records = []
    
    for _ in range(int(input())):
        name = input()
        score = float(input())
        records.append([name, score])
        
    min_num = records[0][1]
    min_num2 = None
    for el in records:
        if el[1] < min_num:
            min_num2 = min_num
            min_num = el[1]
        elif el[1] > min_num and (min_num2 is None or el[1] < min_num2):
            min_num2 = el[1]
        
    for el in sorted([el[0] for el in records if el[1] == min_num2]):
        print(el)

5
Harry
37.21
Berry
37.21
Tina
37.2
Akriti
41
Harsh
39
Berry
Harry


Finding the percentage

In [12]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    print(f"{sum(student_marks[query_name])/len(student_marks[query_name]):.2f}")

3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


Lists

In [14]:
if __name__ == '__main__':
    N = int(input())
    l = []
    
    for _ in range(N):
        command = input().split()
        if command[0] == 'insert':
            l.insert(int(command[1]), int(command[2]))
        elif command[0] == 'print':
            print(l)
        elif command[0] == 'remove':
            l.remove(int(command[1]))
        elif command[0] == 'append':
            l.append(int(command[1]))
        elif command[0] == 'sort':
            l = sorted(l)
        elif command[0] == 'pop':
            l.pop()
        elif command[0] == 'reverse':
            l = l[::-1]

12
insert 0 5
insert 1 10
insert 0 6
print
[6, 5, 10]
remove 6
append 9
append 1
sort
print
[1, 5, 9, 10]
pop
reverse
print
[9, 5, 1]


Tuples

In [15]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t = tuple(integer_list)
    print(hash(t))

2
1 2
3713081631934410656


## Strings

sWAP cASE

In [16]:
def swap_case(s):
    return s.swapcase()

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

HackerRank.com presents "Pythonist 2".
hACKERrANK.COM PRESENTS "pYTHONIST 2".


String Split and Join

In [17]:
def split_and_join(line):
    return("-".join(line.split(" ")))

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is a string   
this-is-a-string---


What's Your Name?

In [18]:
#
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    # Write your code here
    print(f"Hello {first} {last}! You just delved into python.")

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)

Ross
Taylor
Hello Ross Taylor! You just delved into python.


Mutations

In [19]:
def mutate_string(string, position, character):
    return string[:position] + character + string[position+1:]

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)

abracadabra
5 k
abrackdabra


Find a string

In [20]:
def count_substring(string, sub_string):
    c = 0
    for i in range(len(string) - len(sub_string) + 1):
        if string[i:i+len(sub_string)] == sub_string:
            c += 1  
    return c

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)

ABCDCDC
CDC
2


String Validators

In [21]:
if __name__ == '__main__':
    s = input()
    flags = [False] * 5
    
    for ch in s:
        flags[0] |= ch.isalnum()
        flags[1] |= ch.isalpha()
        flags[2] |= ch.isdigit()
        flags[3] |= ch.islower()
        flags[4] |= ch.isupper()
    
    for el in flags:
        print(el)

qA2
True
True
True
True
True


Text Alignment

In [24]:
#Replace all ______ with rjust, ljust or center. 

thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))    

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


Text Wrap

In [22]:
import textwrap

def wrap(string, max_width):
    return "\n".join(textwrap.wrap(string, max_width))

if __name__ == '__main__':
    string, max_width = input(), int(input())
    result = wrap(string, max_width)
    print(result)

ABCDEFGHIJKLMNOPQRSTUVWXYZ
4
ABCD
EFGH
IJKL
MNOP
QRST
UVWX
YZ


Designer Door Mat

In [23]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n, m = map(int, input().split())

for i in range(n // 2):
    def_length = (m - 3 * (i * 2 + 1)) // 2
    print('-' * def_length + '.|.' * (i * 2 + 1) + '-' * def_length)

def_length_wel = (m - 7) // 2
print('-' * def_length_wel + 'WELCOME' + '-' * def_length_wel)

for i in range(n // 2 - 1, -1, -1):
    def_length = (m - 3 * (i * 2 + 1)) // 2
    print('-' * def_length + '.|.' * (i * 2 + 1) + '-' * def_length)

7 21
---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


String Formatting

In [25]:
def print_formatted(number):
    for i in range(1, number + 1):
        print('{0:{max_len}d} {0:{max_len}o} {0:{max_len}X} {0:{max_len}b}'\
              .format(i, max_len = len(bin(number)) - 2))

if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

5
  1   1   1   1
  2   2   2  10
  3   3   3  11
  4   4   4 100
  5   5   5 101


Alphabet Rangoli

In [26]:
def print_rangoli(size):
    # your code goes here
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    half_width = (size - 1) * 2
    
    for i in range(size):
        line = ''
        for j in range(i):
            line += alphabet[size - 1 - j] + '-'
        print((half_width - i * 2) * '-' + \
                line + alphabet[size - 1 - i] + line[::-1] + \
                (half_width - i * 2) * '-')
    
    for i in range(size - 2, -1, -1):
        line = ''
        for j in range(i):
            line += alphabet[size - 1 - j] + '-'
        print((half_width - i * 2) * '-' + \
                line + alphabet[size - 1 - i] + line[::-1] + \
                (half_width - i * 2) * '-')

if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

5
--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------


Capitalize!

In [27]:
#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    return re.sub(r'\b([a-z])', 
            lambda x: x.group(1).upper(), s)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()


KeyError: 'OUTPUT_PATH'

The Minion Game

In [28]:
def minion_game(string):
    # your code goes here
    stuart = 0
    kevin = 0
    
    for i in range(len(string)):
        if string[i] in 'AEIOU':
            kevin += len(string) - i
        else:
            stuart += len(string) - i
            
    if kevin > stuart:
        print('Kevin', kevin)
    elif stuart > kevin:
        print('Stuart', stuart)
    else:
        print('Draw')        
    

if __name__ == '__main__':
    s = input()
    minion_game(s)

BANANA
Stuart 12


Merge the Tools!

In [29]:
def merge_the_tools(string, k):
    # your code goes here
    for i in range(0, len(string), k):
        line = ''
        for j in range(min(k, len(string) - i)):
            if string[i + j] not in (string[i:i+j]):
                line += string[i + j]
        print(line)

if __name__ == '__main__':
    string, k = input(), int(input())
    merge_the_tools(string, k)

AABCAAADA
3
AB
CA
AD


## Sets

Introduction to Sets

In [30]:
def average(array):
    # your code goes here
    arr_set = set(array)
    return(sum(arr_set) / len(arr_set))

if __name__ == '__main__':
    n = int(input())
    arr = list(map(int, input().split()))
    result = average(arr)
    print(result)

10
161 182 161 154 176 170 167 171 170 174
169.375


Symmetric Difference

In [1]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
m = int(input())
m_set = set(map(int, input().split()))
n = int(input())
n_set = set(map(int, input().split()))

for el in sorted((n_set | m_set) - (n_set & m_set)):
    print(el)

4
2 4 5 9
4
2 4 11 12
5
9
11
12


No Idea!

In [2]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n, m = map(int, input().split())
arr = list(map(int, input().split()))
a = set(map(int, input().split()))
b = set(map(int, input().split()))

print(sum([1 if el in a else -1 if el in b else 0 for el in arr]))

3 2
1 5 3
3 1
5 7
1


Set .add()

In [3]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
stamps = set()

for _ in range(n):
    stamps.add(input())
    
print(len(stamps))

7
UK
China
USA
France
New Zealand
UK
France
5


Set .discard(), .remove() & .pop()

In [4]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
s = set(map(int, input().split()))
m = int(input())

for _ in range(m):
    command = input().split()
    if command[0] == 'pop':
        s.pop()
    elif command[0] == 'remove':
        s.remove(int(command[1]))
    elif command[0] == 'discard':
        s.discard(int(command[1]))
        
print(sum(s))

9
1 2 3 4 5 6 7 8 9
10
pop 
remove 9 
discard 9 
discard 8 
remove 7 
pop  
discard 6 
remove 5 
pop  
discard 5
4


Set .union() Operation

In [7]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
s = set(map(int, input().split()))
m = int(input())
t = set(map(int, input().split()))

print(len(s | t))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
13


Set .intersection() Operation

In [8]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
s = set(map(int, input().split()))
m = int(input())
t = set(map(int, input().split()))

print(len(s & t))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
5


Set .difference() Operation

In [9]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
s = set(map(int, input().split()))
m = int(input())
t = set(map(int, input().split()))

print(len(s - t))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
4


Set .symmetric_difference() Operation

In [10]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
s = set(map(int, input().split()))
m = int(input())
t = set(map(int, input().split()))

print(len(s ^ t))

9
1 2 3 4 5 6 7 8 9
9
10 1 2 3 11 21 55 6 8
8


Set Mutations

In [11]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n = int(input())
s = set(map(int, input().split()))
m = int(input())

for _ in range(m):
    command = input().split()
    t = set(map(int, input().split()))
    if command[0] == 'intersection_update':
        s &= t
    elif command[0] == 'update':
        s |= t
    elif command[0] == 'difference_update':
        s -= t
    elif command[0] == 'symmetric_difference_update':
        s ^= t

print(sum(s))

 16  
1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52  
4  
intersection_update 10  
2 3 5 6 8 9 1 4 7 11  
update 2  
55 66  
symmetric_difference_update 5  
22 7 35 62 58  
difference_update 7  
11 22 35 55 58 62 66
38


The Captain's Room

In [13]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
k = int(input())
arr = list(map(int, input().split()))
s = set(arr)

for el in s:
    arr.remove(el)

print((s - set(arr)).pop())

5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
8


Check Subset

In [14]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
t = int(input())
for _ in range(t):
    n = int(input())
    n_set = set(map(int, input().split()))
    m = int(input())
    m_set = set(map(int, input().split()))
    
    print(len(set(n_set) - set(m_set)) == 0)

3 
5 
1 2 3 5 6 
9 
9 8 5 6 3 2 1 4 7 
True
1 
2 
5 
3 6 5 4 1 
False
7 
1 2 3 5 6 8 9 
3 
9 8 2
False


Check Strict Superset

In [15]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
a = set(map(int, input().split()))
n = int(input())
flag = True

for _ in range(n):
    b = set(map(int, input().split()))
    flag &= (len(b - a) == 0)
    
print(flag)

1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
2 
1 2 3 4 5 
100 11 12
False


## Collections

collections.Counter()

In [16]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import Counter

n = int(input())
c = Counter(map(int, input().split()))

m = int(input())
s = 0
for _ in range(m):
    x, cost = map(int, input().split())
    if c[x] > 0:
        s += cost
        c[x] -= 1
        
print(s)

10 
2 3 4 5 6 8 7 6 5 18 
6 
6 55 
6 45 
6 55 
4 40 
18 60 
10 50
200


DefaultDict Tutorial

In [17]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import defaultdict

n, m = map(int, input().split())
d = defaultdict(list)

for i in range(n):
    d[input()].append(str(i + 1))
    
for _ in range(m):
    line = input()
    print(" ".join(d[line]) if len(d[line]) > 0 else -1)

5 2
a
a
b
a
b
a
1 2 4
b
3 5


Collections.namedtuple()

In [18]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import namedtuple
n = int(input())
Student = namedtuple("student", " ".join(input().split()))

student_marks = []
for _ in range(n):
    stud = Student(*(input().split()))
    student_marks.append(int(stud.MARKS))
    
print(sum(student_marks) / len(student_marks))

5
ID         MARKS      NAME       CLASS     
1          97         Raymond    7         
2          50         Steven     4         
3          91         Adrian     9         
4          72         Stewart    5         
5          80         Peter      6   
78.0


Collections.OrderedDict()

In [19]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import OrderedDict

n = int(input())
item_dict = OrderedDict()
for _ in range(n):
    item = input().split()
    item_name = " ".join(item[:-1])
    item_price = int(item[-1])
    if item_name in item_dict.keys():
        item_dict[item_name] += item_price
    else:
        item_dict[item_name] = item_price
        
for key in item_dict:
    print(key, item_dict[key])

9 
BANANA FRIES 12 
POTATO CHIPS 30 
APPLE JUICE 10 
CANDY 5 
APPLE JUICE 10 
CANDY 5 
CANDY 5 
CANDY 5 
POTATO CHIPS 30
BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


Word Order

In [20]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import OrderedDict

n = int(input())
word_dict = OrderedDict()
for _ in range(n):
    word = input()
    if word in word_dict.keys():
        word_dict[word] += 1
    else:
        word_dict[word] = 1
        
print(len(word_dict))
print(" ".join([str(word) for word in word_dict.values()]))

4 
bcdef
abcdefg
bcde
bcdef
3
2 1 1


Collections.deque()

In [21]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque

d = deque()
n = int(input())
for _ in range(n):
    command = input().split()
    if command[0] == 'append':
        d.append(int(command[1]))
    elif command[0] == 'appendleft':
        d.appendleft(int(command[1]))
    elif command[0] == 'pop':
        d.pop()
    elif command[0] == 'popleft':
        d.popleft()
print(" ".join([str(el) for el in d]))

6 
append 1 
append 2 
append 3 
appendleft 4 
pop 
popleft
1 2


Piling Up!

In [23]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from collections import deque

t = int(input())
for _ in range(t):
    n = int(input())
    d = deque(map(int, input().split()))
    
    if n <= 2:
        print("Yes")
        continue
        
    left = d.popleft()
    right = d.pop()
    top = 0
    if left < right:
        top = right
        right = d.pop()
    else:
        top = left
        left = d.popleft()
        
    while len(d) > 0:
        if top < left or top < right:
            break
            
        if left < right:
            top = right
            right = d.pop()
        else:
            top = left
            left = d.popleft()
    
    if top < left or top < right:
        print("No")
    else:
        print("Yes")

2
6
4 3 2 1 3 4
Yes
3
1 3 2
No


Company Logo

In [24]:
#!/bin/python3

import math
import os
import random
import re
import sys

from collections import Counter

if __name__ == '__main__':
    s = sorted(input())
    c = Counter(s)
    for el in c.most_common(3):
        print(el[0], el[1])


aabbbccde
b 3
a 2
c 2


## Date and Time

Calendar Module

In [25]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import calendar

month, day, year = map(int, input().split())
week = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY",
        "FRIDAY", "SATURDAY", "SUNDAY"]
print(week[calendar.weekday(year, month, day)])

08 05 2015
WEDNESDAY


Time Delta

In [28]:
#!/bin/python3

import math
import os
import random
import re
import sys

import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    return str(abs(int((datetime.datetime
                        .strptime(t1, '%a %d %b %Y %H:%M:%S %z') -
                        datetime.datetime
                        .strptime(t2, '%a %d %b %Y %H:%M:%S %z'))
                        .total_seconds())))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()

KeyError: 'OUTPUT_PATH'

## Errors and Exceptions

Exceptions

In [29]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
t = int(input())
for _ in range(t):
    try:
        a, b = map(int, input().split())
        print(a // b)
    except ZeroDivisionError as e:
        print("Error Code:", e)
    except ValueError as e:
        print("Error Code:", e)

3
1 0
Error Code: integer division or modulo by zero
2 $
Error Code: invalid literal for int() with base 10: '$'
3 1
3


## Built-Ins

Zipped!

In [30]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
n, x = map(int, input().split())
marks = []
for _ in range(x):
    marks += [list(map(float, input().split()))]

for el in zip(*marks):
    print(round(sum(el) / len(el), 1))

5 3
89 90 78 93 80
90 91 85 88 86
91 92 83 89 90.5
90.0
91.0
82.0
90.0
85.5


Athlete Sort

In [31]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())

    sorted_arr = sorted(arr, key=lambda x: x[k])
    print("\n".join([" ".join(str(x) for x in arr_el)
                    for arr_el in sorted_arr]))

5 3
10 2 5
7 1 0
9 9 9
1 23 12
6 5 9
1
7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


ginortS

In [32]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from functools import cmp_to_key

def compare(a, b):
    if a.isupper() and b.islower():
        return 1
    if a.islower() and b.isupper():
        return -1
    
    if a.isnumeric() and b.isalpha():
        return 1
    if a.isalpha() and b.isnumeric():
        return -1
    
    if a.isnumeric() and b.isnumeric():
        odds = '13579'
        return (1 if a not in odds and b in odds 
                else -1 if a in odds and b not in odds 
                else 1 if a > b else -1 if a < b else 0)
    
    return 1 if a > b else -1 if a < b else 0

s = input()
print(''.join(sorted(s, key=cmp_to_key(compare))))

Sorting1234
ginortS1324


## Python Functionals

Map and Lambda Function

In [33]:
cube = lambda x: x**3# complete the lambda function 

def fibonacci(n):
    # return a list of fibonacci numbers
    fib = [0, 1]
    if n <= 2:
        return fib[:n]
        
    for _ in range(2, n):
        fib.append(fib[-1] + fib[-2])
    return fib

if __name__ == '__main__':
    n = int(input())
    print(list(map(cube, fibonacci(n))))

5
[0, 1, 1, 8, 27]


## Regex and Parsing

Detect Floating Point Number

In [34]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

pattern = re.compile(r"^[+-]?\d*\.\d+$")
t = int(input())
for _ in range(t):
    print(re.match(pattern, input()) is not None)

4
4.0O0
False
-1.00
True
+4.54
True
SomeRandomStuff
False


Re.split()

In [35]:
regex_pattern = r"[,\.]"	# Do not delete 'r'.

import re
print("\n".join(re.split(regex_pattern, input())))

100,000,000.000
100
000
000
000


Group(), Groups() & Groupdict()

In [38]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

res = re.search(r"(([a-zA-Z0-9])\2)", input())
if res is None:
    print(-1)
else:
    print(res.group(1)[0])

..12345678910111213141516171820212223
1


Re.findall() & Re.finditer()

In [39]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

pattern = re.compile(r"[bcdfghjklmnpqrstvwxyzBCDFGJKLMNPQRSTVWXYZ]" +
                     r"[aeiouAEIOU]{2,}" + 
                     r"(?=[bcdfghjklmnpqrstvwxyzBCDFGJKLMNPQRSTVWXYZ])")
res = re.findall(pattern, input())
if len(res) == 0:
    print(-1)
else:
    for el in res:
        print(el[1:])

rabcdeefgyYhFjkIoomnpOeorteeeeet
ee
Ioo
Oeo
eeeee


Re.start() & Re.end()

In [40]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

s = input()
k = input()

res = re.search(k, s)
if res is None:
    print("(-1, -1)")
    
p = -1
while res is not None:
    p += res.start() + 1
    print("({0}, {1})".format(p, p + res.end() - res.start() - 1))
    res = re.search(k, s[p + 1:])

aaadaa
aa
(0, 1)
(1, 2)
(4, 5)


Regex Substitution

In [41]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

n = int(input())
for _ in range(n):
    print(re.sub(r" &&(?= )", " and",
          re.sub(r" \|\|(?= )", " or", input())))

11
a = 1;
a = 1;
b = input();
b = input();


if a + b > 0 && a - b < 0:
if a + b > 0 and a - b < 0:
    start()
    start()
elif a*b > 10 || a/b < 1:
elif a*b > 10 or a/b < 1:
    stop()
    stop()
print set(list(a)) | set(list(b)) 
print set(list(a)) | set(list(b)) 
#Note do not change &&& or ||| or & or |
#Note do not change &&& or ||| or & or |
#Only change those '&&' which have space on both sides.
#Only change those '&&' which have space on both sides.
#Only change those '|| which have space on both sides.
#Only change those '|| which have space on both sides.


Validating Roman Numerals

In [42]:
regex_pattern = r"^(?=[MDCLXVI])M{0,3}(C[MD]|D?C{0,3})(X[CL]|L?X{0,3})(I[XV]|V?I{0,3})$"	# Do not delete 'r'.

import re
print(str(bool(re.match(regex_pattern, input()))))

CDXXI
True


Validating phone numbers

In [43]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

pattern = re.compile(r"^[789]\d{9}$")
n = int(input())
for _ in range(n):
    if re.match(pattern, input()):
        print("YES")
    else:
        print("NO")

2
9587456281
YES
1252478965
NO


Validating and Parsing Email Addresses

In [44]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re
from email.utils import formataddr, parseaddr

pattern = re.compile(r"^[a-zA-Z][\w\-\.]+\@[a-zA-Z]+\.[a-zA-Z]{0,3}$")
n = int(input())
for _ in range(n):
    line = parseaddr(input())
    if re.match(pattern, line[1]):
        print(formataddr(line))

2
DEXTER <dexter@hotmail.com>
DEXTER <dexter@hotmail.com>
VIRUS <virus!@variable.:p>


Hex Color Code

In [45]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

pattern = re.compile(r"[:; ,\()]\#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})(?=[:; ,\n\)])")
n = int(input())
for _ in range(n):
    for el in re.findall(pattern, input()):
        print("#" + el)

11 
#BED
{
    color: #FfFdF8; background-color:#aef;
#FfFdF8
#aef
    font-size: 123px;
    background: -webkit-linear-gradient(top, #f9f9f9, #fff);
#f9f9f9
#fff
}
#Cab
{
    background-color: #ABC;
#ABC
    border: 2px dashed #fff;
#fff
}


HTML Parser - Part 1

In [46]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        for pair in attrs:
            print("-> {0} > {1}".format(pair[0], pair[1]))
        
    def handle_endtag(self, tag):
        print("End   :", tag)
        
    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        for pair in attrs:
            print("-> {0} > {1}".format(pair[0], pair[1]))
            
n = int(input())
parser = MyHTMLParser()
for _ in range(n):
    parser.feed(input())

2
<html><head><title>HTML Parser - I</title></head>
Start : html
Start : head
Start : title
End   : title
End   : head
<body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


HTML Parser - Part 2

In [47]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        comment = data.split("\n")
        if len(comment) == 1:
            print(">>> Single-line Comment")
        else:
            print(">>> Multi-line Comment")
        for el in comment:
            print(el)
        
    def handle_data(self, data):
        if len(data.strip()) == 0:
            return
        print(">>> Data")
        print(data)
  
  
html = ""
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()

4
<!--[if IE 9]>IE9-specific content
<![endif]-->
<div> Welcome to HackerRank</div>
<!--[if IE 9]>IE9-specific content<![endif]-->
>>> Multi-line Comment
[if IE 9]>IE9-specific content
<![endif]
>>> Data
 Welcome to HackerRank
>>> Single-line Comment
[if IE 9]>IE9-specific content<![endif]


Detect HTML Tags, Attributes and Attribute Values

In [48]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        for pair in attrs:
            print("-> {0} > {1}".format(pair[0], pair[1]))
        
    def handle_startendtag(self, tag, attrs):
        print(tag)
        for pair in attrs:
            print("-> {0} > {1}".format(pair[0], pair[1]))
            
n = int(input())
parser = MyHTMLParser()
string = ''
for _ in range(n):
    string += input() + "\n"

parser.feed(string)

9
<head>
<title>HTML</title>
</head>
<object type="application/x-flash" 
  data="your-file.swf" 
  width="0" height="0">
  <!-- <param name="movie" value="your-file.swf" /> -->
  <param name="quality" value="high"/>
</object>
head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


Validating UID

In [49]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

pattern = re.compile(r"^(?=(?:[0-9a-z]*[A-Z]){2})(?=(?:[a-zA-Z]*[0-9]){3})(?:([0-9a-zA-Z])(?!.*\1)){10}$")
n = int(input())
for _ in range(n):
    if re.match(pattern, input()):
        print('Valid')
    else:
        print('Invalid')

2
B1CD102354
Invalid
B1CDEF2354
Valid


Validating Credit Card Numbers

In [50]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import re

pattern = re.compile(r"^(?!.*([0-9])\1\1\1)[456](?:[0-9]){15}$")
n = int(input())
for _ in range(n):
    line = input()
    if len(line) == 19 and line[4] == '-' and\
       line[9] == '-' and line[14] == '-':
       line = line[:4] + line[5:9] + line[10:14] + line[15:]
       
    if re.match(pattern, line):
        print("Valid")
    else:
        print("Invalid")

6
4123456789123456
Valid
5123-4567-8912-3456
Valid
61234-567-8912-3456
Invalid
4123356789123456
Valid
5133-3367-8912-3456
Invalid
5123 - 3567 - 8912 - 3456
Invalid


Validating Postal Codes

In [51]:
regex_integer_in_range = r"^[1-9]([0-9]){5}$"  # Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(.)(?=.\1)"  # Do not delete 'r'.


import re
P = input()

print (bool(re.match(regex_integer_in_range, P)) 
and len(re.findall(regex_alternating_repetitive_digit_pair, P)) < 2)

110000
False


Matrix Script

In [52]:
#!/bin/python3

import math
import os
import random
import re
import sys




first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)
    
print(re.sub(r"([0-9a-zA-Z])[^0-9a-zA-Z]+(?=[0-9a-zA-Z])", r"\1 ",
      "".join([x[i] for i in range(m) for x in matrix])))

7 3
Tsi
h%x
i #
sM 
$a 
#t%
ir!
This is Matrix#  %!


## XML

XML 1 - Find the Score

In [53]:
import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    # your code goes here
    s = len(node.attrib)
    for el in node:
        s += get_attr_number(el)
        
    return s

if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

ParseError: no element found: line 1, column 0 (<string>)

XML2 - Find the Maximum Depth

In [54]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    # your code goes here
    if level + 1 > maxdepth:
        maxdepth = level + 1
    for el in elem:
        depth(el, level + 1)

if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

6
<feed xml:lang='en'>
    <title>HackerRank</title>
    <subtitle lang='en'>Programming challenges</subtitle>
    <link rel='alternate' type='text/html' href='http://hackerrank.com/'/>
    <updated>2013-12-25T12:00:00</updated>
</feed>
1


## Closures and Decorations

Standardize Mobile Number Using Decorators

In [55]:
def wrapper(f):
    def fun(l):
        # complete the function
        for i in range(len(l)):
            if len(l[i]) == 10:
                l[i] = "+91 " + l[i][:5] + " " + l[i][5:]
            elif len(l[i]) == 11 and l[i][0] == '0':
                l[i] = "+91 " + l[i][1:6] + " " + l[i][6:]
            elif len(l[i]) == 12 and l[i].startswith("91"):
                l[i] = "+91 " + l[i][2:7] + " " + l[i][7:]
            elif len(l[i]) == 13 and l[i].startswith("+91"):
                l[i] = "+91 " + l[i][3:8] + " " + l[i][8:]
        return f(l)
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 




3
07895462130
919875641230
9195969878
+91 78954 62130
+91 91959 69878
+91 98756 41230


Decorators 2 - Name Directory

In [56]:
import operator

def person_lister(f):
    def inner(people):
        # complete the function
        return [f(el) for el in sorted(people, key=lambda x: int(x[2]))]
        
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

3
Mike Thomson 20 M
Robert Bustle 32 M
Andria Bustle 30 F
Mr. Mike Thomson
Ms. Andria Bustle
Mr. Robert Bustle


## Numpy

Arrays

In [57]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    return numpy.array(arr[::-1], float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


Shape and Reshape

In [58]:
import numpy as np

print(np.array(input().split(), int).reshape((3, 3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Transpose and Flatten

In [59]:
import numpy as np

n, m = map(int, input().split())

arr = []
for _ in range(n):
    arr.append(list(map(int, input().split())))
    
arr_np = np.array(arr)
print(arr_np.T)
print(arr_np.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


Concatenate

In [60]:
import numpy as np

n, m, p = map(int, input().split())

n_p = []
for _ in range(n):
    n_p.append(list(map(int, input().split())))

m_p = []
for _ in range(m):
    m_p.append(list(map(int, input().split())))
    
print(np.concatenate((np.array(n_p), np.array(m_p)), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


Zeros and Ones

In [62]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
import numpy as np

shape = list(map(int, input().split()))

print(np.zeros(shape, dtype=int))
print(np.ones(shape, dtype=int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Eye and Identity

In [63]:
import numpy as np

np.set_printoptions(legacy='1.13')
print(np.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Array Mathematics

In [64]:
import numpy as np

n, m = map(int, input().split())

a_list = []
for _ in range(n):
    a_list.append(input().split())
a_arr = np.array(a_list, int)

b_list = []
for _ in range(n):
    b_list.append(input().split())
b_arr = np.array(b_list, int)
    
print(a_arr + b_arr)
print(a_arr - b_arr)
print(a_arr * b_arr)
print(a_arr // b_arr)
print(a_arr % b_arr)
print(a_arr ** b_arr)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


Floor, Ceil and Rint

In [65]:
import numpy as np

np.set_printoptions(legacy='1.13')
arr = np.array(input().split(), float)
print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


Sum and Prod

In [66]:
import numpy as np

n, m = map(int, input().split())
arr_list = []
for _ in range(n):
    arr_list.append(input().split())
arr = np.array(arr_list, int)
print(np.prod(np.sum(arr, axis=0)))

2 2
1 2
3 4
24


Min and Max

In [67]:
import numpy as np

n, m = map(int, input().split())
arr_list = []
for _ in range(n):
    arr_list.append(input().split())
arr = np.array(arr_list, int)
print(np.max(np.min(arr, axis=1)))

4 2
2 5
3 7
1 3
4 0
3


Mean, Var, and Std

In [70]:
import numpy as np

n, m = map(int, input().split())
arr_list = []
for _ in range(n):
    arr_list.append(input().split())
arr = np.array(arr_list, int)
print(np.round(np.mean(arr, axis=1), 11))
print(np.round(np.var(arr, axis=0), 11))
print(np.round(np.std(arr, axis=None), 11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


Dot and Cross

In [71]:
import numpy as np

n = int(input())

a_list = []
for _ in range(n):
    a_list.append(input().split())
a_arr = np.array(a_list, int)

b_list = []
for _ in range(n):
    b_list.append(input().split())
b_arr = np.array(b_list, int)

print(a_arr.dot(b_arr))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


Inner and Outer

In [72]:
import numpy as np

a = np.array(input().split(), int)
b = np.array(input().split(), int)
print(np.inner(a, b))
print(np.outer(a, b))

0 1
2 3
3
[[0 0]
 [2 3]]


Polynomials

In [73]:
import numpy as np

p_arr = np.array(input().split(), float)
x = float(input())

print(np.polyval(p_arr, x))

1.1 2 3
0
3.0


Linear Algebra

In [75]:
import numpy as np

n = int(input())
a = []
for _ in range(n):
    a.append(input().split())
arr = np.array(a, float)

print(round(np.linalg.det(arr), 2))

2
1.1 1.1
1.1 1.1
0.0


# Problem 2

Birthday Cake Candles

In [76]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles):
    # Write your code here
    return candles.count(max(candles))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()


KeyError: 'OUTPUT_PATH'

Number Line Jumps

In [77]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    # Write your code here
    delta_first = abs(x1 - x2)
    delta_second = delta_first- abs(x1 + v1 - x2 - v2)
    if delta_second > 0 and delta_first % delta_second == 0:
        return "YES"
    else:
        return "NO"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    fptr.write(result + '\n')

    fptr.close()


KeyError: 'OUTPUT_PATH'

Viral Advertising

In [1]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    # Write your code here
    cumul = 2
    s = 5
    for el in range(n - 1):
        s = s // 2 * 3
        cumul += s // 2
    return cumul

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()


KeyError: 'OUTPUT_PATH'

Recursive Digit Sum

In [2]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    # Write your code here
    if len(n) == 1 and int(n) * k < 10:
        return int(n) * k
        
    return superDigit(str(sum([int(el) for el in n]) * k), 1)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()


KeyError: 'OUTPUT_PATH'

Insertion Sort - Part 1

In [3]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    if n == 1:
        print(arr)
        return
    
    x = arr[-1]
    n = n - 2
    arr[-1] = arr[-2]
    while n > 0 and arr[n] > x:
        print(" ".join([str(ch) for ch in arr]))
        arr[n] = arr[n-1]
        n -= 1
    if arr[n] > x:
        print(" ".join([str(ch) for ch in arr]))
        arr[0] = x
    else:
        arr[n + 1] = x
    print(" ".join([str(ch) for ch in arr]))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)


5
2 4 6 8 3
2 4 6 8 8
2 4 6 6 8
2 4 4 6 8
2 3 4 6 8


Insertion Sort - Part 2

In [4]:
#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort2(n, arr):
    # Write your code here
    for i in range(2, n + 1):
        if i == 1:
            print(" ".join([str(ch) for ch in arr]))
            continue
        
        x = arr[i-1]
        k = i - 2
        arr[i-1] = arr[i-2]
        while k > 0 and arr[k] > x:
            arr[k] = arr[k-1]
            k -= 1
        if arr[k] > x:
            arr[0] = x
        else:
            arr[k + 1] = x
        print(" ".join([str(ch) for ch in arr]))

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)


6
1 4 3 5 6 2
1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
